[package]
name = "reword"
version = "0.1.0"
authors = ["Pawin Vongmasa <pawin.vongmasa@gmail.com>"]
edition = "2018"

[dependencies]

[dev-dependencies]
criterion = "0.3.3"

[[bench]]
name = "bench_main"
harness = false
